services:
  - type: web
    name: telegram-voiceflow-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'main:app' --bind=0.0.0.0:$PORT --worker-class=gthread --workers=1 --threads=4
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VOICEFLOW_API_KEY
        sync: false
      - key: VOICEFLOW_PROJECT_ID
        sync: false
      - key: REDIS_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
