services:
  - type: web
    name: telegram-voiceflow-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VOICEFLOW_API_KEY
        sync: false
      - key: VOICEFLOW_PROJECT_ID
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 10000
    autoDeploy: true
